#!/usr/bin/env bash
# One-command install: bring up the quillmark-mcp stack with docker compose,
# clear any poisoned Claude Code OAuth cache, and register the server with
# Claude Code via `claude mcp add --transport http`.
#
# Usage:
#   ./scripts/install-mcp.sh                   # default port 8080
#   ./scripts/install-mcp.sh --port 9090       # custom host port
#   ./scripts/install-mcp.sh --no-claude       # skip claude mcp add step
#
# Idempotent: re-running refreshes the Claude Code registration but leaves
# a healthy stack alone.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

PORT="${QUILLMARK_HOST_PORT:-8080}"
SKIP_CLAUDE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --port)        PORT="$2"; shift 2 ;;
    --port=*)      PORT="${1#*=}"; shift ;;
    --no-claude)   SKIP_CLAUDE=1; shift ;;
    -h|--help)
      sed -n '2,11p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "unknown flag: $1" >&2
      exit 2
      ;;
  esac
done

# --- output helpers ---
if [ -t 1 ]; then
  C_BLUE='\033[1;34m'; C_GREEN='\033[1;32m'; C_RED='\033[1;31m'; C_YELLOW='\033[1;33m'; C_OFF='\033[0m'
else
  C_BLUE=''; C_GREEN=''; C_RED=''; C_YELLOW=''; C_OFF=''
fi
banner() { printf '\n%b━━━ %s ━━━%b\n' "$C_BLUE" "$*" "$C_OFF"; }
ok()     { printf '%b✓ %s%b\n' "$C_GREEN" "$*" "$C_OFF"; }
warn()   { printf '%b! %s%b\n' "$C_YELLOW" "$*" "$C_OFF"; }
fail()   { printf '\n%b✗ %s%b\n' "$C_RED" "$*" "$C_OFF"; exit 1; }
have()   { command -v "$1" >/dev/null 2>&1; }

# =============================================================================
# Pre-flight
# =============================================================================
banner "Pre-flight"
have docker || fail "docker CLI not found"
docker info >/dev/null 2>&1 || fail "docker daemon not reachable — is Docker Desktop running?"
docker compose version >/dev/null 2>&1 || fail "'docker compose' plugin not available"
ok "docker + compose ready"

if have claude; then
  ok "claude CLI found"
else
  warn "claude CLI not found — will skip Claude Code registration step"
  SKIP_CLAUDE=1
fi

# =============================================================================
# Build image if missing
# =============================================================================
banner "Build image"
if docker image inspect quillmark-mcp:dev >/dev/null 2>&1; then
  ok "quillmark-mcp:dev already built (use 'docker compose build' to refresh)"
else
  docker build -t quillmark-mcp:dev . || fail "docker build failed"
  ok "built quillmark-mcp:dev"
fi

# =============================================================================
# Generate per-port compose override if needed
# =============================================================================
OVERRIDE_FILE="docker-compose.override.yml"
if [ "$PORT" != "8080" ]; then
  cat > "$OVERRIDE_FILE" <<EOF
# Auto-generated by scripts/install-mcp.sh — do not commit.
services:
  quillmark-mcp:
    ports:
      - "127.0.0.1:${PORT}:8080"
    environment:
      QUILLMARK_BASE_URL: http://127.0.0.1:${PORT}/artifacts
EOF
  ok "generated ${OVERRIDE_FILE} for host port ${PORT}"
elif [ -f "$OVERRIDE_FILE" ]; then
  rm -f "$OVERRIDE_FILE"
  ok "removed stale ${OVERRIDE_FILE} (using default port 8080)"
fi

# =============================================================================
# Start the stack
# =============================================================================
banner "Start stack"
docker compose up -d || fail "docker compose up failed"

# Wait for health
deadline=$(( $(date +%s) + 30 ))
status=""
while [ "$(date +%s)" -lt "$deadline" ]; do
  status="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' quillmark-mcp 2>/dev/null || echo unknown)"
  case "$status" in
    healthy|running) break ;;
  esac
  sleep 0.25
done
if [ "$status" != "healthy" ] && [ "$status" != "running" ]; then
  docker compose logs --tail 40 quillmark-mcp || true
  fail "container did not become healthy within 30s (last status: $status)"
fi
ok "container status: $status"

# =============================================================================
# Reset cache + register with Claude Code
# =============================================================================
if [ "$SKIP_CLAUDE" -eq 1 ]; then
  warn "skipping Claude Code registration"
else
  banner "Register with Claude Code"
  ./scripts/claude-reset.sh quillmark
  claude mcp remove quillmark 2>/dev/null || true
  claude mcp add --transport http quillmark "http://127.0.0.1:${PORT}/mcp" \
    || fail "'claude mcp add' failed"
  ok "registered quillmark → http://127.0.0.1:${PORT}/mcp"
fi

# =============================================================================
# Success banner
# =============================================================================
banner "Done"
cat <<EOF

  ${C_GREEN}✓${C_OFF} quillmark-mcp is running at http://127.0.0.1:${PORT}/mcp
$( [ "$SKIP_CLAUDE" -eq 0 ] && printf '  %b✓%b Claude Code is connected\n' "$C_GREEN" "$C_OFF" )

  Verify:
    docker compose ps
$( [ "$SKIP_CLAUDE" -eq 0 ] && printf '    claude mcp list | grep quillmark\n' )
    curl -s http://127.0.0.1:${PORT}/.well-known/oauth-protected-resource

  Use it:
    Open Claude Code and ask it to list quills, or render a memo.

  Tear down:
    ./scripts/uninstall-mcp.sh              # keep image + volume
    ./scripts/uninstall-mcp.sh --yes --purge  # remove everything

EOF
