#!/usr/bin/env bash
# One-command install for quillmark-mcp.
#
# Brings the server up (HTTP via docker compose, or per-session stdio via
# docker run) and prints the Claude Code / Codex snippet you need to paste.
# No user config files are modified.
#
# Supported clients: claude-code, codex.
#
# Usage:
#   ./scripts/install-mcp.sh                                 # HTTP mode, print both snippets
#   ./scripts/install-mcp.sh --target claude-code            # HTTP mode, one client only
#   ./scripts/install-mcp.sh --target codex --mode stdio
#   ./scripts/install-mcp.sh --mode http --port 9090
#   ./scripts/install-mcp.sh --no-server                     # skip bring-up, just print snippets
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

MODE="http"
PORT="${QUILLMARK_HOST_PORT:-8080}"
TARGET="all"
SKIP_SERVER=0
NAME="quillmark"
IMAGE="quillmark-mcp:dev"

usage() {
  sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode)        MODE="$2"; shift 2 ;;
    --mode=*)      MODE="${1#*=}"; shift ;;
    --http)        MODE="http"; shift ;;
    --stdio)       MODE="stdio"; shift ;;
    --port)        PORT="$2"; shift 2 ;;
    --port=*)      PORT="${1#*=}"; shift ;;
    --target)      TARGET="$2"; shift 2 ;;
    --target=*)    TARGET="${1#*=}"; shift ;;
    --name)        NAME="$2"; shift 2 ;;
    --name=*)      NAME="${1#*=}"; shift ;;
    --no-server)   SKIP_SERVER=1; shift ;;
    -h|--help)     usage; exit 0 ;;
    *)
      echo "unknown flag: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

case "$MODE" in http|stdio) ;; *) echo "--mode must be 'http' or 'stdio' (got: $MODE)" >&2; exit 2 ;; esac

if [ -t 1 ]; then
  C_BLUE=$'\033[1;34m'; C_GREEN=$'\033[1;32m'; C_RED=$'\033[1;31m'; C_YELLOW=$'\033[1;33m'; C_DIM=$'\033[2m'; C_OFF=$'\033[0m'
else
  C_BLUE=''; C_GREEN=''; C_RED=''; C_YELLOW=''; C_DIM=''; C_OFF=''
fi
banner() { printf '\n%s━━━ %s ━━━%s\n' "$C_BLUE" "$*" "$C_OFF"; }
subbanner() { printf '\n%s── %s ──%s\n' "$C_DIM" "$*" "$C_OFF"; }
ok()     { printf '%s✓ %s%s\n' "$C_GREEN" "$*" "$C_OFF"; }
warn()   { printf '%s! %s%s\n' "$C_YELLOW" "$*" "$C_OFF"; }
fail()   { printf '\n%s✗ %s%s\n' "$C_RED" "$*" "$C_OFF"; exit 1; }
have()   { command -v "$1" >/dev/null 2>&1; }

# =============================================================================
# Pre-flight
# =============================================================================
banner "Pre-flight"
have docker || fail "docker CLI not found"
docker info >/dev/null 2>&1 || fail "docker daemon not reachable — is Docker Desktop running?"
ok "docker ready"

have node || fail "node not found (required for snippet generator)"
ok "node ready"

# =============================================================================
# Always rebuild image to pick up code changes
# =============================================================================
banner "Image"
if docker image inspect "$IMAGE" >/dev/null 2>&1; then
  docker rmi "$IMAGE" >/dev/null 2>&1 || true
  ok "removed stale $IMAGE"
fi
docker build -t "$IMAGE" . || fail "docker build failed"
ok "built $IMAGE"

# =============================================================================
# Artifacts dir — always created so file:// URLs work in stdio mode,
# and so HTTP mode can bind-mount it if the user wants host-visible output.
# =============================================================================
ARTIFACTS_DIR="$HOME/.quillmark/artifacts"
mkdir -p "$ARTIFACTS_DIR"
ok "artifacts dir: $ARTIFACTS_DIR"

# =============================================================================
# Bring the server up (HTTP mode only — stdio mode has nothing to start)
# =============================================================================
URL="http://127.0.0.1:${PORT}/mcp"

if [ "$SKIP_SERVER" -eq 0 ] && [ "$MODE" = "http" ]; then
  banner "Start server (HTTP, docker compose)"
  docker compose version >/dev/null 2>&1 || fail "'docker compose' plugin required for --http mode"

  OVERRIDE_FILE="docker-compose.override.yml"
  if [ "$PORT" != "8080" ]; then
    cat > "$OVERRIDE_FILE" <<EOF
# Auto-generated by scripts/install-mcp.sh — do not commit.
services:
  quillmark-mcp:
    ports:
      - "127.0.0.1:${PORT}:8080"
    environment:
      QUILLMARK_BASE_URL: http://127.0.0.1:${PORT}/artifacts
EOF
    ok "generated ${OVERRIDE_FILE} for host port ${PORT}"
  elif [ -f "$OVERRIDE_FILE" ]; then
    rm -f "$OVERRIDE_FILE"
  fi

  docker compose up -d || fail "docker compose up failed"

  deadline=$(( $(date +%s) + 30 ))
  status=""
  while [ "$(date +%s)" -lt "$deadline" ]; do
    status="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' quillmark-mcp 2>/dev/null || echo unknown)"
    case "$status" in healthy|running) break ;; esac
    sleep 0.25
  done
  if [ "$status" != "healthy" ] && [ "$status" != "running" ]; then
    docker compose logs --tail 40 quillmark-mcp || true
    fail "container did not become healthy within 30s (last status: $status)"
  fi
  ok "container status: $status"
  ok "MCP endpoint: $URL"
elif [ "$SKIP_SERVER" -eq 0 ] && [ "$MODE" = "stdio" ]; then
  banner "Stdio mode — no long-lived server"
  ok "each client session will spawn its own container via 'docker run -i --rm'"
fi

# =============================================================================
# Write .mcp.json for auto-discovery by Claude Code, Cursor, Cline, etc.
# =============================================================================
MCP_JSON="$ROOT_DIR/.mcp.json"
cat > "$MCP_JSON" <<EOF
{
  "mcpServers": {
    "${NAME}": {
      "type": "http",
      "url": "${URL}"
    }
  }
}
EOF
ok "wrote ${MCP_JSON} (auto-discovered by Claude Code, Cursor, Cline)"

# =============================================================================
# Print snippets
# =============================================================================
CONFIG_ARGS=(
  --name "$NAME"
  --url "$URL"
  --artifacts-dir "$ARTIFACTS_DIR"
)

ALL_CLIENTS=(claude-code codex)

case "$TARGET" in
  all|claude-code|codex) ;;
  *) fail "--target must be one of: all, claude-code, codex (got: $TARGET)" ;;
esac

print_snippet() {
  local client="$1"
  local mode="$2"
  subbanner "$client ($mode)"
  node src/bin.js config "$client" --mode "$mode" "${CONFIG_ARGS[@]}" || {
    warn "snippet generation failed for $client/$mode"
    return 0
  }
}

banner "Client snippets"

if [ "$TARGET" = "all" ]; then
  printf '\n  Copy the block below into the config file your client expects.\n'
  for client in "${ALL_CLIENTS[@]}"; do
    print_snippet "$client" "$MODE"
  done
else
  print_snippet "$TARGET" "$MODE"
fi

# =============================================================================
# Success banner
# =============================================================================
banner "Done"
cat <<EOF

  ${C_GREEN}✓${C_OFF} quillmark-mcp is ready.
EOF

if [ "$MODE" = "http" ] && [ "$SKIP_SERVER" -eq 0 ]; then
  cat <<EOF
  ${C_GREEN}✓${C_OFF} HTTP server running at ${URL}
  ${C_GREEN}✓${C_OFF} Artifacts: ${ARTIFACTS_DIR}

  Verify: curl ${URL} -H 'accept: application/json, text/event-stream' -d '{}'
  Stop:   ./scripts/uninstall-mcp.sh --yes

EOF
else
  cat <<EOF
  ${C_GREEN}✓${C_OFF} Image built. Snippets above are ready to paste.

EOF
fi
